server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      discovery:
        enabled: true
      loadbalancer:
        enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auths/**
            - id: member
              uri: lb://member
              predicates:
                - Path=/members/**
            - id: recipe
              uri: lb://recipe
              predicates:
                - Path=/recipes/**

whitelist:
  service:
    - "auths"
  api:
    recipes:
      - method: GET
        path: "/"
  swagger-path:
    - "/swagger-ui"
    - "/v3/api-docs"
    - "/swagger-resources"
    - "/webjars"

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET}

logging:
  level:
    org.springframework.web: DEBUG