server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      discovery:
        enabled: true
      loadbalancer:
        enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: auth
              uri: lb://auth
              predicates:
                - Host=auth.tsrecipe.shop
            - id: member
              uri: lb://member
              predicates:
                - Host=member.tsrecipe.shop
            - id: recipe
              uri: lb://recipe
              predicates:
                - Host=recipe.tsrecipe.shop

auth-ignore:
  host:
    - "auth"
  api:
    recipe:
      - "/"
    member:
      - "/"

external-service-url:
  auth: "http://auth:8010"

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET}